### ISSUE TITLE
Decision Tree Pipeline Endpoint

### ISSUE THREAD

**Issue by nolankurylo** [SENG499-S22-Company3/algorithm-2#41]
- Create a POST Endpoint in the flask app that accepts the following inputs and return the following outputs to the client:

  - Input: list of courses to be offered for the current semester and their course number 
     - {courses_to_predict:[CSC111, SENG265...], semester: F,Sp,Su)}

  - Output: {CSC111:200, SENG265:61, ...}
     - key: value --> course: predicted class size

Detailed Function (Pipeline) description:
- engineer features based on input classes and semester
- preprocess to the same format as the training dataset
- model prediction on each row (course to be offered)
     - load model (.pkl)
- return outputs

**Comment by DavidOkulski** [comment]
Predict class size endpoint has been created:
```
curl -X POST -H "Content-Type: application/json" -d '{
    { "subject": <COURSE SUBJECT>,
     "code": <COURSE CODE>,
      "seng_ratio": <RATIO OF SENG STUDENTS>,
      "semester": <SEMESTER>,
      "capacity": <CAPICITY OF COURSE>}
}' http://localhost:5000/predict_class_size
```

 The required fields are "subject" (string), "code" (string), "seng_ratio" (int), "semester" (string), and "capacity" (int).

 The capacity of the course must be set to 0 for the machine learning model to predict a course capcity, or else the same capacity value will be returned.
