### ISSUE TITLE
Commit Template

### ISSUE THREAD

**Issue by nolankurylo** [SENG499-S22-Company3/algorithm-2#49]

**Comment by Scault** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Schedulater-629034391c13f00017e43cce/issues/SENG499-S22-Company3/algorithm-2/49?planning-poker) with ZenHub @Scault

**Comment by Scault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Schedulater-629034391c13f00017e43cce/issues/SENG499-S22-Company3/algorithm-2/49?planning-poker) with ZenHub @BaraaDawod @DavidOkulski @Randon511 @nolankurylo
