### ISSUE TITLE
Retrain/update class size predictive model when there is an update the historical data

### ISSUE THREAD

**Issue by nolankurylo** [SENG499-S22-Company3/algorithm-2#6]
Preprocessing would then be followed by updating the prediction algorithm / (maybe even continuing to train a machine learning model).

This includes adding or removing historical data.

**Comment by BaraaDawod** [comment]
I recommend rewording the issue title to: "As an Admin, I want the Class Size Prediction Machine Learning model to be retrained when I make update the historical data"
